---
- name: "POC: Sistema de Monitoreo y Respuesta Automatizada"
  hosts: webserver

  sources:
    - name: Alert Receiver
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /emergency

  rules:
    #- name: Debug - Mostrar todas las alertas recibidas
    #  condition: true
    #  action:
    #    debug:
    #      msg: "Alerta recibida: {{ event }}"

    - name: CPU alto detectado
      condition: >
        event.payload.metric_type == "cpu" and 
        event.payload.value >= 90
      action:
        run_playbook:
          name: playbooks/cpu_alto.yml
          extra_vars:
            cpu_usage: "{{ event.payload.value }}"
            host_afectado: "{{ event.payload.host }}"
            timestamp: "{{ event.payload.timestamp }}"

    - name: Alerta de poco espacio en disco
      condition: >
        event.payload.metric_type == "disk" and 
        event.payload.value >= 90
      action:
        run_playbook:
          name: playbooks/poco_espacio_disco.yml
          extra_vars:
            disk_usage: "{{ event.payload.value }}"
            host_afectado: "{{ event.payload.host }}"
            timestamp: "{{ event.payload.timestamp }}"

    - name: Alerta de memoria insuficiente
      condition: >
        event.payload.metric_type == "memory" and 
        event.payload.value >= 85
      action:
        run_playbook:
          name: playbooks/memoria_insuficiente.yml
          extra_vars:
            memory_usage: "{{ event.payload.value }}"
            host_afectado: "{{ event.payload.host }}"
            timestamp: "{{ event.payload.timestamp }}"
