---
- name: Monitorear y sanar servidor web
  hosts: webserver

  sources:
    - name: Verificar el estado del sitio cada 5 segundos
      ansible.eda.url_check:
        urls:
          - http://192.168.56.10
        delay: 5

  rules:
    - name: El sitio está caído - condición múltiple
      condition: >
        event.url_check.status != "up"
      action:
        run_playbook:
          name: playbooks/reiniciar_nginx.yml