---
- name: "Prueba: Lanzar Demo Job de AWX con un Webhook"
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Palabra clave 'demo_job' detectada
      condition: event.payload.action == "demo_job"
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: "Default"
